spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5433/airlinesDB
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true